import { Router } from 'express';
import productsRouter from '../routers/products.js';
import nearestStoreRouter from '../routers/nearestStore.js';
import storeRouter from '../routers/stores.js';
import reviewsRouter from '../routers/reviews.js';
import usersRouter from '../routers/auth.js';
import ordersRouter from '../routers/orders.js';
const router = Router();
router.use('/api/products', productsRouter);
router.use('/api/stores/nearest', nearestStoreRouter);
router.use('/api/stores', storeRouter);
router.use('/api/customer-reviews', reviewsRouter);
router.use('/api/user', usersRouter);
router.use('/api/cart', ordersRouter);
export default router;
